version: "3.8"
services:
  redis:
    image: redis:7.0
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD?Not set}
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis_data:/data
  
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./storage/elastic_data:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  
  
  api:
    restart: always
    container_name: api
    build:
      context: .
      dockerfile: ./Docker/api.dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./storage:/usr/src/app/storage
    depends_on:
      - elastic
    env_file:
      - .env
  worker:
    deploy:
      mode: replicated
      replicas: 2   # since it was mention in assignment to make it scalable, we can use this to increase/decrease number of workers required.
    build:
      context: .
      dockerfile: ./Docker/worker.dockerfile
    volumes:
      - ./storage:/usr/src/app/storage
      - ./config/supervisord.conf:/etc/supervisord.conf
    depends_on:
      - redis
      - elastic
    env_file:
      - .env